services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow:
    build: ./airflow
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW_HOME: /opt/airflow
      LLM_API_KEY: ${LLM_API_KEY}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./spark:/opt/spark_app
      - ./output:/opt/output
      - ./scraper:/opt/project/scraper
      - ./agent:/opt/project/agent
      - ./agent_price:/opt/project/agent_price
    command: standalone

  spark:
    build: ./spark
    container_name: spark-etl
    volumes:
      - ./spark:/opt/spark_app
      - ./output:/opt/output
    working_dir: /opt/spark_app
    command: tail -f /dev/null

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 minioadmin minioadmin &&
      mc mb -p local/tayara-raw || true &&
      mc mb -p local/tayara-processed || true &&
      exit 0
      "

volumes:
  postgres-db-volume:
    external: true
    name: etl_postgres-db-volume