import os
import json
import time
import uuid
import cohere
from src.ingestion.setup_db import get_qdrant_client
from qdrant_client.models import VectorParams, Distance, PointStruct
from dotenv import load_dotenv

# Import config (adjust path if your folder structure differs)
try:
    from config.settings import QDRANT_URL, QDRANT_API_KEY, COHERE_API_KEY
except ImportError:
    # Fallback to direct env access if settings.py isn't configured
    load_dotenv()
    QDRANT_API_KEY = os.getenv("QDRANT_API_KEY")
    COHERE_API_KEY = os.getenv("COHERE_API_KEY")

class LawIndexer:
    def __init__(self, collection_name="tunisian_laws"):
        self.co = cohere.Client(os.getenv("COHERE_API_KEY"))
        self.qdrant = get_qdrant_client()
        self.collection_name = collection_name
        self.batch_size = 50

    def _ensure_collection(self):
        """Creates the Qdrant collection if it doesn't exist."""
        if not self.qdrant.collection_exists(self.collection_name):
            print(f"🏗️ Creating collection: {self.collection_name}")
            self.qdrant.create_collection(
                collection_name=self.collection_name,
                vectors_config=VectorParams(size=1024, distance=Distance.COSINE),
            )

    def load_parsed_data(self, file_path):
        """Loads chunks from the JSONL file produced by the parser."""
        chunks = []
        with open(file_path, "r", encoding="utf-8") as f:
            for line in f:
                if line.strip():
                    chunks.append(json.loads(line))
        return chunks

    def embed_chunks(self, chunks):
        """Generates embeddings and attaches them to the chunks."""
        # We prepend breadcrumb for better legal context during retrieval
        texts = [f"{c.get('breadcrumb', 'Source')} : {c['text']}" for c in chunks]
        all_vectors = []

        print(f"🔢 Generating embeddings for {len(chunks)} sections...")
        for i in range(0, len(texts), self.batch_size):
            batch = texts[i : i + self.batch_size]
            response = self.co.embed(
                texts=batch,
                model="embed-multilingual-v3.0",
                input_type="search_document"
            )
            all_vectors.extend(response.embeddings)
            print(f"✅ Embedded {len(all_vectors)}/{len(chunks)}...")
            time.sleep(0.5)

        for chunk, vector in zip(chunks, all_vectors):
            chunk["vector"] = vector
        
        return chunks

    def upload_to_qdrant(self, embedded_chunks):
        """Converts chunks to Qdrant points and uploads them."""
        self._ensure_collection()
        
        points = []
        print(f"🚀 Preparing upload for {len(embedded_chunks)} points...")
        
        for chunk in embedded_chunks:
            # Create a deterministic UUID based on the text to avoid duplicates
            point_id = str(uuid.uuid5(uuid.NAMESPACE_DNS, chunk['text'] + chunk['id']))
            
            points.append(PointStruct(
                id=point_id,
                vector=chunk["vector"],
                payload={
                    "text": chunk["text"],
                    "article_id": chunk["id"],
                    "breadcrumb": chunk["breadcrumb"],
                    "source": chunk["source"]
                }
            ))

        # Upload in batches
        for i in range(0, len(points), self.batch_size):
            batch = points[i : i + self.batch_size]
            self.qdrant.upsert(
                collection_name=self.collection_name,
                points=batch,
                wait=True
            )
            print(f"📤 Uploaded batch starting at {i}...")

    def run(self, input_jsonl):
        """Main execution flow."""
        start_time = time.time()
        
        # 1. Load
        raw_chunks = self.load_parsed_data(input_jsonl)
        
        # 2. Embed
        embedded_data = self.embed_chunks(raw_chunks)
        
        # 3. Upload
        self.upload_to_qdrant(embedded_data)
        
        end_time = time.time()
        print(f"🎯 SUCCESS! Ingestion took {round(end_time - start_time, 2)} seconds.")


if __name__ == "__main__":
    indexer = LawIndexer()
    # Path to the JSONL file generated by your UnifiedLegalIngestor
    indexer.run("test_output.jsonl")